## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:5432/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: always
    
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
# Hibernate ddl auto (create, create-drop, validate, update)

    hibernate:
      ddl-auto: update
      


#  profiles:
#    active:
#    - @spring.profiles.active@   
      
server:
  port: 9696
  servlet:
    context-path: /easynotes

  

  
