## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:  datasource:    url: jdbc:postgresql://192.168.99.100:5432/coursedb
    username: postgres
    password: mysecretpassword
    
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
# Hibernate ddl auto (create, create-drop, validate, update)

    hibernate:      ddl-auto: update
      

#  profiles:
#    active:
#    - @spring.profiles.active@   
      
server:  port: 9696
  
